apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01-v2-deployment
  labels:
    app: app01-v2
    version: '2'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app01-v2
  template:
    metadata:
      labels:
        app: app01-v2
    spec:
      containers:
      - name: app01-v2
        image: 325583868777.dkr.ecr.us-east-1.amazonaws.com/k8s-lab:v02
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: app01-v2
        resources:
          requests:
            cpu: '20m'
            memory: '100Mi'
          limits:
            cpu: '20m'
            memory: '100Mi'